version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-seguros
    environment:
      POSTGRES_DB: seguros_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: application-seguros
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/seguros_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - JPA_DDL_AUTO=update
    depends_on:
      - db

volumes:
  postgres_data:
